spring:
  application:
    name: CMSFORCE
    
server:
  port: 9002
  
---
spring:
  profile: local
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jpa:
     hibernate:
      show-sql: false
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    
---
spring:
  profile: dev
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jpa:
     hibernate:
      show-sql: false
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    
---
spring:
  profile: prod
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jpa:
     hibernate:
      show-sql: false
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  
          
      



